# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0024_internshipspeciality_order_postion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipoffer',
            name='master',
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='internship_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipMaster'),
        ),
    ]
